name: Update Contributors

on:
  push:
    branches: [main, dev]
  schedule:
    - cron: "0 0 * * 0" # Every Sunday at midnight UTC

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Update Contributors in README.md
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 90
          columns_per_row: 7
          auto_detect_branch_protection: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Contributors in README_CN.md
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 90
          columns_per_row: 7
          readme_path: README_CN.md
          auto_detect_branch_protection: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Contributors in README_JP.md
        uses: akhilmhdh/contributors-readme-action@v2.3.11
        with:
          image_size: 90
          columns_per_row: 7
          readme_path: README_JP.md
          auto_detect_branch_protection: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
